#!/bin/bash
bk_host=host
bk_ftp_user=user
bk_ftp_pass=pass
bk_ftp_port=21
bk_ftp_path=/home/files/bd
# suponeos que usamos .my.cnf si no lo usamos lo creamos... easy... más seguro y universalmente compatible
if [ ! -d ~/tmp ];then
mkdir ~/tmp
fi
cd ~/tmp
databases=$(echo "show databases;" | mysql |grep -v performance_schema)

for bd in $databases
do
echo "Respaldando $bd"
/usr/local/bin/mysqldump $bd > $bd.sql
echo "Comprimiendo $bd"
gzip $bd.sql
echo "Transfiriendo $bd"
/usr/local/bin/lftp -c "open -u $bk_ftp_user,$bk_ftp_pass ftp://$bk_host -p $bk_ftp_port; put -O $bk_ftp_path $bd.sql.gz "
rm -f $bd.sql.gz
done
